### ISSUE TITLE
model CMCC-ESM2 not reported in ES-DOC-INSTITUTIONAL-cmcc and issue during CDF2CIM publications

### ISSUE THREAD

**Issue by esgf-cmcc** [ES-DOC-INSTITUTIONAL/cmcc#1]
Hi all,
during esgf publication of CMCC-ESM2 datasets, the CDF2CIM publication fails with: 

WEB-SERVICE ERROR: 400 :: {"errorCode": 900, "errorMessage": "u'CMCC-ESM2' is not one of [u'4AOP-v1-5', u'4aop-v1-5', u'ACCESS-CM2'......

It seams that the procedure of es-doc publication don't find model CMCC-ESM2 registered in ES-DOC-INSTITUTIONAL/cmcc. This happens because the CMCC update model CMCC-ESM2-SR5 to CMCC-ESM2 in CMIP6 CVs.

can someone clarify me?

It seams @momipsl reported all cmcc cmip6 modules, is there a procedure to report or update modules?

Thanks

**Comment by davidhassell** [comment]
Hi,

There seems to be two things going on here, The cdf2cim issue is a result of the CMIP6 CVs being imported by PREPARE on the ESGF publication node being out of date. I see that the model name change only happened ~2 months ago (https://github.com/WCRP-CMIP/CMIP6_CVs/pull/847/commits/86587dcd413bbcea79a5b14d1d2257074f27b1d4). Is PREPARE up to date?

The cdf2cim process is wholly independent from the ES-DOC institutional repository (https://github.com/ES-DOC-INSTITUTIONAL/cmcc). However, the institutional repository will need updating to reflect this recent change in the CMIP6 CV. I was not aware of the change, so ES-DOC will review its process of monitoring for inconsistencies with CMIP6.

It looks like no model documentation has been created for CMCC-ESM2-SR5 (assessed by only a  look) so creating new spreadsheets for the description of CMCC-ESM2 should be easy.

Have any datasets with the name CMCC-ESM2-SR5 already been ingested into ESGF?

Thanks,
David

**Comment by esgf-cmcc** [comment]
Hi David,
it's a pleasure to hear from you.
On our esgf node, the python environment used to publish is named "esgf-publ". Today I tried to update this environment, to create a new one, or update some packages like "cmor", "cdf2cim" (cmor contains PrePARE), but this not resolve my issue. Which is the correct way to update PrePARE library? If I use PrePARE specifying the latest cmor tables download, the PrePARE toll work well: "PrePARE --table-path CMOR/Tables /data/products/ESGF/"
(I sent you more details in cdf2cim@es-doc.org mail).

Regarding datasets, all published CMCC-ESM2-SR5 are retracted. No CMCC-ESM2-SR5 datesets are now ingested in ESGF.
Regarding "retract", which is the procedure to retract old publication with cdf2cim?

Regards,
Giuseppe.

**Comment by esgf-cmcc** [comment]
Regarding CDF2CIM and error 400, without any intervention on my node, since yesterday the cdf2cim procedure has started to work (I think someone registered the CMCC-ESM2 model, but I don't know where). Now I have published all the datasets. I only miss the CDF2CIM revert procedure since for some files I had to revert to esgf.
